In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
data = pd.read_csv('E:\Admission_Predict.csv')
data.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [3]:
x=data.drop(['Chance of Admit '],axis=1) 
y=data['Chance of Admit ']

In [4]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15)

In [5]:
x_train

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
114,115,311,105,3,3.5,3.0,8.45,1
12,13,328,112,4,4.0,4.5,9.10,1
268,269,327,113,4,4.5,5.0,9.14,0
362,363,338,115,5,4.5,5.0,9.23,1
182,183,299,100,2,3.0,3.5,7.88,0
...,...,...,...,...,...,...,...,...
237,238,329,114,5,4.5,5.0,9.19,1
84,85,340,115,5,4.5,4.5,9.45,1
224,225,305,105,2,3.0,2.0,8.23,0
65,66,325,112,4,3.5,3.5,8.92,0
78,79,296,95,2,3.0,2.0,7.54,1

In [6]:
y_train

114    0.59
12     0.78
268    0.83
362    0.91
182    0.68
       ...
237    0.86
84     0.94
224    0.67
65     0.55
78     0.44
Name: Chance of Admit , Length: 340, dtype: float64

In [7]:
x_test

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
14,15,311,104,3,3.5,2.0,8.20,1
312,313,311,107,4,4.5,4.5,9.00,1
398,399,312,103,3,3.5,4.0,8.78,0
377,378,290,100,1,1.5,2.0,7.56,0
59,60,311,104,2,2.0,2.0,8.30,0
180,181,300,104,3,3.5,3.0,8.16,0
109,110,304,103,5,5.0,4.0,8.64,0
309,310,308,110,4,3.5,3.0,8.60,0
281,282,317,110,3,4.0,4.5,9.11,1
255,256,307,110,4,4.0,4.5,8.37,0
124,125,301,106,4,2.5,3.0,8.47,0
36,37,299,106,2,4.0,4.0,8.40,0
32,33,338,118,4,3.0,4.5,9.40,1
103,104,317,104,2,4.5,4.0,8.47,0
303,304,323,107,3,3.5,3.5,8.55,1
29,30,310,99,2,1.5,2.0,7.30,0
245,246,328,110,4,4.0,2.5,9.02,1
54,55,322,110,3,3.0,3.5,8.00,0
347,348,299,94,1,1.0,1.0,7.34,0
174,175,321,111,4,4.0,4.0,8.97,1
111,112,321,109,4,4.0,4.0,8.68,1
323,324,305,102,2,2.0,2.5,8.18,0
157,158,309,104,2,2.0,2.5,8.26,0
315,316,308,104,2,2.5,3.0,8.07,0
321,322,323,104,3,4.0,4.0,8.44,1
369,370,301,98,1,2.0,3.0,8.03,1
200,201,317,103,3,2.5,3.0,8.54,1
207,208,310,102,3,3.5,4.0,8.02,1
366,367,320,104,3,3.5,4.5,8.34,1
267,268,314,107,3,3.0,3.5,8.17,1
240,241,296,101,1,2.5,3.0,7.68,0
344,345,295,96,2,1.5,2.0,7.34,0
49,50,327,111,4,3.0,4.0,8.40,1
85,86,319,103,4,4.5,3.5,8.66,0
378,379,303,98,1,2.0,2.5,7.65,0
386,387,302,101,2,2.5,3.5,7.96,0
352,353,303,100,2,3.0,3.5,8.06,1
145,146,320,113,2,2.0,2.5,8.64,1
318,319,324,111,3,2.5,2.0,8.80,1
76,77,327,112,3,3.0,3.0,8.72,1
285,286,331,116,5,4.0,4.0,9.26,1
294,295,316,101,2,2.5,2.0,8.32,1
235,236,326,111,5,4.5,4.0,9.23,1
233,234,304,100,2,2.5,3.5,8.07,0
168,169,293,97,2,2.0,4.0,7.80,1
204,205,298,105,3,3.5,4.0,8.54,0
113,114,320,110,2,4.0,3.5,8.56,0
178,179,309,108,3,2.5,3.0,8.12,0
55,56,320,103,3,3.0,3.0,7.70,0
188,189,331,115,5,4.5,3.5,9.36,1
335,336,325,111,4,4.0,4.5,9.11,1
322,323,314,107,2,2.5,4.0,8.27,0
10,11,325,106,3,3.5,4.0,8.40,1
35,36,320,110,5,5.0,5.0,9.20,1
45,46,322,110,5,5.0,4.0,9.10,1
9,10,323,108,3,3.5,3.0,8.60,0
343,344,305,103,2,2.5,3.5,8.13,0
123,124,308,108,3,3.5,3.5,8.22,0
381,382,319,105,3,3.0,3.5,8.67,1
140,141,329,110,2,4.0,3.0,9.15,1

In [8]:
y_test

14     0.61
312    0.78
398    0.67
377    0.47
59     0.42
180    0.71
109    0.68
309    0.70
281    0.80
255    0.79
124    0.57
36     0.64
32     0.91
103    0.57
303    0.73
29     0.54
245    0.81
54     0.70
347    0.42
174    0.87
111    0.69
323    0.62
157    0.65
315    0.65
321    0.73
369    0.67
200    0.73
207    0.66
366    0.74
267    0.73
240    0.60
344    0.47
49     0.78
85     0.76
378    0.56
386    0.46
352    0.64
145    0.81
318    0.79
76     0.74
285    0.93
294    0.61
235    0.88
233    0.64
168    0.64
204    0.69
113    0.72
178    0.72
55     0.64
188    0.93
335    0.83
322    0.72
10     0.52
35     0.88
45     0.88
9      0.45
343    0.59
123    0.61
381    0.73
140    0.84
Name: Chance of Admit , dtype: float64

In [9]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor()
model.fit(x_train,y_train)

GradientBoostingRegressor()

In [10]:
model.score(x_test,y_test)

0.7529479419591305

In [11]:
y_predict=model.predict(x_test)

In [12]:
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error
import numpy as np
print('Mean Absolute Error:', mean_absolute_error(y_test, y_predict))  
print('Mean Squared Error:', mean_squared_error(y_test, y_predict))  
print('Root Mean Squared Error:', np.sqrt(mean_squared_error(y_test, y_predict)))

Mean Absolute Error: 0.04214741214063922
Mean Squared Error: 0.003930159039771494
Root Mean Squared Error: 0.06269098052967025

In [13]:
y_train = (y_train>0.5)
y_test = (y_test>0.5)

In [14]:
from sklearn.linear_model._logistic import LogisticRegression

lore = LogisticRegression(random_state=0, max_iter=1000)

lr = lore.fit(x_train, y_train)

In [15]:
y_pred = lr.predict(x_test)

In [16]:
y_pred

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])