In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('E:\Admission_Predict.csv')
data.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [3]:
x=data.drop(['Chance of Admit '],axis=1) 
y=data['Chance of Admit ']

In [4]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15)

In [5]:
x_train

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
129,130,333,118,5,5.0,5.0,9.35,1
133,134,323,112,5,4.0,4.5,8.78,0
168,169,293,97,2,2.0,4.0,7.80,1
203,204,334,120,5,4.0,5.0,9.87,1
94,95,303,99,3,2.0,2.5,7.66,0
...,...,...,...,...,...,...,...,...
333,334,319,108,3,3.0,3.5,8.54,1
224,225,305,105,2,3.0,2.0,8.23,0
15,16,314,105,3,3.5,2.5,8.30,0
20,21,312,107,3,3.0,2.0,7.90,1
0,1,337,118,4,4.5,4.5,9.65,1

In [6]:
y_train

129    0.92
133    0.79
168    0.64
203    0.97
94     0.36
       ...
333    0.71
224    0.67
15     0.54
20     0.64
0      0.92
Name: Chance of Admit , Length: 340, dtype: float64

In [7]:
x_test

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
36,37,299,106,2,4.0,4.0,8.40,0
87,88,317,107,2,3.5,3.0,8.28,0
137,138,316,100,2,1.5,3.0,8.16,1
186,187,317,107,3,3.5,3.0,8.68,1
222,223,324,113,4,4.5,4.0,8.79,0
46,47,329,114,5,4.0,5.0,9.30,1
55,56,320,103,3,3.0,3.0,7.70,0
242,243,324,115,3,3.5,3.0,8.76,1
90,91,318,106,2,4.0,4.0,7.92,1
254,255,321,114,4,4.0,5.0,9.12,0
283,284,321,111,3,2.5,3.0,8.90,1
259,260,331,119,4,5.0,4.5,9.34,1
338,339,323,108,5,4.0,4.0,8.74,1
346,347,304,97,2,1.5,2.0,7.64,0
211,212,328,110,4,5.0,4.0,9.14,1
111,112,321,109,4,4.0,4.0,8.68,1
363,364,306,103,2,2.5,3.0,8.36,0
225,226,296,99,2,2.5,2.5,8.03,0
169,170,311,99,2,2.5,3.0,7.98,0
304,305,313,106,2,2.5,2.0,8.43,0
205,206,295,99,2,2.5,3.0,7.65,0
374,375,315,105,2,2.0,2.5,7.65,0
146,147,315,105,3,2.0,2.5,8.48,0
238,239,310,104,3,2.0,3.5,8.37,0
123,124,308,108,3,3.5,3.5,8.22,0
262,263,308,103,2,2.5,4.0,8.36,1
187,188,335,118,5,4.5,3.5,9.44,1
302,303,322,105,2,3.0,3.0,8.45,1
315,316,308,104,2,2.5,3.0,8.07,0
177,178,319,110,3,3.5,3.5,9.04,0
209,210,301,104,3,3.5,4.0,8.12,1
171,172,334,117,5,4.0,4.5,9.07,1
293,294,312,98,1,3.5,3.0,8.18,1
32,33,338,118,4,3.0,4.5,9.40,1
167,168,313,102,3,2.0,3.0,8.27,0
310,311,320,104,3,3.0,3.5,8.74,1
68,69,318,109,3,3.5,4.0,9.22,1
49,50,327,111,4,3.0,4.0,8.40,1
260,261,327,108,5,5.0,3.5,9.13,1
399,400,333,117,4,5.0,4.0,9.66,1
181,182,305,107,2,2.5,2.5,8.42,0
93,94,301,97,2,3.0,3.0,7.88,1
334,335,312,107,4,4.5,4.0,8.65,1
276,277,329,113,5,5.0,4.5,9.45,1
358,359,314,105,2,2.5,2.0,7.64,0
390,391,314,102,2,2.0,2.5,8.24,0
48,49,321,110,3,3.5,5.0,8.85,1
120,121,335,117,5,5.0,5.0,9.56,1
197,198,310,106,2,3.5,2.5,8.33,0
379,380,311,99,1,2.5,3.0,8.43,1
296,297,310,107,3,3.5,3.5,8.67,0
10,11,325,106,3,3.5,4.0,8.40,1
313,314,301,100,3,3.5,3.0,8.04,0
62,63,304,105,2,3.0,3.0,8.20,1
244,245,314,107,2,2.5,4.0,8.56,0
184,185,316,106,2,2.5,4.0,8.32,0
204,205,298,105,3,3.5,4.0,8.54,0
166,167,302,102,3,3.5,5.0,8.33,0
156,157,315,105,3,2.0,2.5,8.34,0
47,48,339,119,5,4.5,4.0,9.70,0

In [8]:
y_test

36     0.64
87     0.66
137    0.71
186    0.84
222    0.76
46     0.86
55     0.64
242    0.70
90     0.64
254    0.85
283    0.80
259    0.90
338    0.81
346    0.47
211    0.82
111    0.69
363    0.69
225    0.61
169    0.65
304    0.62
205    0.57
374    0.39
146    0.75
238    0.70
123    0.61
262    0.70
187    0.93
302    0.65
315    0.65
177    0.82
209    0.68
171    0.89
293    0.64
32     0.91
167    0.64
310    0.76
68     0.68
49     0.78
260    0.87
399    0.95
181    0.71
93     0.44
334    0.73
276    0.89
358    0.70
390    0.64
48     0.82
120    0.94
197    0.73
379    0.71
296    0.76
10     0.52
313    0.67
62     0.54
244    0.63
184    0.72
204    0.69
166    0.65
156    0.70
47     0.89
Name: Chance of Admit , dtype: float64